export const USER_SIGNIN_REQUEST = 'USER_SIGNIN_REQUEST';
export const USER_SIGNIN_SUCCES = 'USER_SIGNIN_SUCCES';
export const USER_SIGNIN_FAILED = 'USER_SIGNIN_FAILED';
export const USER_SIGNOUT = 'USER_SIGNIN_SIGNOUT';